/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package LAB2;

import javax.swing.*;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JSlider;


/**
 *
 * @author admin
 */
public class Lab2_Bai4 extends javax.swing.JFrame {
   
   public Lab2_Bai4() {
      initComponents(); 
      this.setResizable(false); // co kich thuoc
      //this.getContentPane().setBackground(Color.orange); // chinh mau
      this.setLocationRelativeTo(null);
      
      // thiết lập định hướng ngang
      sldDoDai.setOrientation(JSlider.HORIZONTAL);
      // Thiết lập maxmin
      sldDoDai.setMaximum(50);
      sldDoDai.setMinimum(0);
      // Thiết lập value mặt định
      sldDoDai.setValue(25);
      // Vạch chia cách 5
      sldDoDai.setMajorTickSpacing(5);
      // Vạch chia phụ mỗi 1
      sldDoDai.setMinorTickSpacing(1);
      // Thiết lâp số
      sldDoDai.setPaintLabels(true);
      // Thiết lập các kẻ vạch
      sldDoDai.setPaintTicks(true);
      
   }
   /**
    * This method is called from within the constructor to initialize the form.
    * WARNING: Do NOT modify this code. The content of this method is always
    * regenerated by the Form Editor.
    */
   @SuppressWarnings("unchecked")
   // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
   private void initComponents() {

      sldDoDai = new javax.swing.JSlider();
      jLabel1 = new javax.swing.JLabel();
      txtValue = new javax.swing.JTextField();
      btnSetValue = new javax.swing.JButton();
      lblfont = new javax.swing.JLabel();

      setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
      addWindowListener(new java.awt.event.WindowAdapter() {
         public void windowActivated(java.awt.event.WindowEvent evt) {
            formWindowActivated(evt);
         }
      });

      sldDoDai.addChangeListener(new javax.swing.event.ChangeListener() {
         public void stateChanged(javax.swing.event.ChangeEvent evt) {
            sldDoDaiStateChanged(evt);
         }
      });

      jLabel1.setText("Giá trị hiện tại:");

      btnSetValue.setText("Set Value");
      btnSetValue.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
            btnSetValueActionPerformed(evt);
         }
      });

      lblfont.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
      lblfont.setForeground(new java.awt.Color(0, 0, 204));
      lblfont.setText("Font Size");

      javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
      getContentPane().setLayout(layout);
      layout.setHorizontalGroup(
         layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(layout.createSequentialGroup()
            .addContainerGap()
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
               .addGroup(layout.createSequentialGroup()
                  .addComponent(sldDoDai, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                  .addGap(14, 14, 14))
               .addGroup(layout.createSequentialGroup()
                  .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                  .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                  .addComponent(txtValue, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                  .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                  .addComponent(btnSetValue)
                  .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 23, Short.MAX_VALUE)
                  .addComponent(lblfont)
                  .addContainerGap())))
      );
      layout.setVerticalGroup(
         layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(layout.createSequentialGroup()
            .addGap(26, 26, 26)
            .addComponent(sldDoDai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(26, 26, 26)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
               .addComponent(jLabel1)
               .addComponent(txtValue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
               .addComponent(btnSetValue))
            .addContainerGap(64, Short.MAX_VALUE))
         .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
            .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(lblfont, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addContainerGap())
      );

      pack();
   }// </editor-fold>//GEN-END:initComponents

   private void btnSetValueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSetValueActionPerformed
      // TODO add your handling code here:
      int value = Integer.parseInt(txtValue.getText());
      sldDoDai.setValue(value);
   }//GEN-LAST:event_btnSetValueActionPerformed

   private void sldDoDaiStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_sldDoDaiStateChanged
      // TODO add your handling code here:
      int value = sldDoDai.getValue();
      txtValue.setText(String.valueOf(value));
     // lblFont.setFont(new java.awt.Font("Tahoma",1,value));      );
   }//GEN-LAST:event_sldDoDaiStateChanged

   private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
      // TODO add your handling code here:
      int value = sldDoDai.getValue();
      txtValue.setText(String.valueOf(value));
   }//GEN-LAST:event_formWindowActivated

   /**
    * @param args the command line arguments
    */
   public static void main(String args[]) {
      /* Set the Nimbus look and feel */
      //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
      /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
       */
      try {
         for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
            if ("Nimbus".equals(info.getName())) {
               javax.swing.UIManager.setLookAndFeel(info.getClassName());
               break;
            }
         }
      } catch (ClassNotFoundException ex) {
         java.util.logging.Logger.getLogger(Lab2_Bai4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
      } catch (InstantiationException ex) {
         java.util.logging.Logger.getLogger(Lab2_Bai4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
      } catch (IllegalAccessException ex) {
         java.util.logging.Logger.getLogger(Lab2_Bai4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
      } catch (javax.swing.UnsupportedLookAndFeelException ex) {
         java.util.logging.Logger.getLogger(Lab2_Bai4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
      }
      //</editor-fold>

      /* Create and display the form */
      java.awt.EventQueue.invokeLater(new Runnable() {
         public void run() {
            new Lab2_Bai4().setVisible(true);
         }
      });
   }

   // Variables declaration - do not modify//GEN-BEGIN:variables
   private javax.swing.JButton btnSetValue;
   private javax.swing.JLabel jLabel1;
   private javax.swing.JLabel lblfont;
   private javax.swing.JSlider sldDoDai;
   private javax.swing.JTextField txtValue;
   // End of variables declaration//GEN-END:variables
}
