/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package LAB2;

import java.awt.Color;
import java.util.ArrayList;
import java.util.Collections;
import java.util.Comparator;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumn;
import javax.swing.table.TableColumnModel;

/**
 *
 * @author admin
 */
public class Lab2_Bai1 extends javax.swing.JFrame {

   /**
    * Creates new form Lab2_Bai1
    */
   
   public static ArrayList<Student> dssv = new ArrayList<Student>();
   
   public Lab2_Bai1() {
      initComponents();
      
      this.setTitle("QUẢN LÝ HỌC VIÊN"); //tieu de
      //this.setSize(500,300); // khung
      this.setResizable(false); // co kich thuoc
      //this.getContentPane().setBackground(Color.orange); // chinh mau
      this.setLocationRelativeTo(null); // chinh o giua
      
      
      String[] data ={"LẬP TRÌNH JAVA","LẬP TRÌNH JAVA 2"
                     ,"THIẾT KẾ WEB","LẬP TRÌNH PYTHON"
            ,"LẬP TRÌNH C#"};
      
      cboKhoaHoc.setModel(new DefaultComboBoxModel(data));
      cboKhoaHoc.setSelectedIndex(0);
      
      
      loadDataToList();
      fillToTable();
      showDetailIndex(0);
      // Chọn hàng thứ nhất khi ứng dụng khởi động
        tblHocVien.setRowSelectionInterval(0, 0);
   }

   /**
    * This method is called from within the constructor to initialize the form.
    * WARNING: Do NOT modify this code. The content of this method is always
    * regenerated by the Form Editor.
    */
   @SuppressWarnings("unchecked")
   // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
   private void initComponents() {

      jScrollPane1 = new javax.swing.JScrollPane();
      jTable1 = new javax.swing.JTable();
      jLabel1 = new javax.swing.JLabel();
      jLabel2 = new javax.swing.JLabel();
      jLabel3 = new javax.swing.JLabel();
      jLabel4 = new javax.swing.JLabel();
      jLabel5 = new javax.swing.JLabel();
      txtName = new javax.swing.JTextField();
      txtDiem = new javax.swing.JTextField();
      txtXepLoai = new javax.swing.JTextField();
      cboKhoaHoc = new javax.swing.JComboBox<>();
      chkThuong = new javax.swing.JCheckBox();
      btnAdd = new javax.swing.JButton();
      btnUpdate = new javax.swing.JButton();
      btnRemove = new javax.swing.JButton();
      btnReset = new javax.swing.JButton();
      jScrollPane2 = new javax.swing.JScrollPane();
      tblHocVien = new javax.swing.JTable();
      btnSXDiem = new javax.swing.JButton();
      btnSXTen = new javax.swing.JButton();

      jTable1.setModel(new javax.swing.table.DefaultTableModel(
         new Object [][] {
            {null, null, null, null},
            {null, null, null, null},
            {null, null, null, null},
            {null, null, null, null}
         },
         new String [] {
            "Title 1", "Title 2", "Title 3", "Title 4"
         }
      ));
      jScrollPane1.setViewportView(jTable1);

      setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

      jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
      jLabel1.setForeground(new java.awt.Color(204, 0, 0));
      jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
      jLabel1.setText("QUẢN LÝ HỌC VIÊN");

      jLabel2.setText("HỌ VÀ TÊN");

      jLabel3.setText("ĐIỂM");

      jLabel4.setText("KHÓA HỌC");

      jLabel5.setText("XẾP LOẠI");

      txtName.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
            txtNameActionPerformed(evt);
         }
      });

      txtXepLoai.setEditable(false);

      cboKhoaHoc.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "dov", "sdvj" }));
      cboKhoaHoc.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
            cboKhoaHocActionPerformed(evt);
         }
      });

      chkThuong.setText("Có phần thưởng?");

      btnAdd.setText("THÊM");
      btnAdd.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
            btnAddActionPerformed(evt);
         }
      });

      btnUpdate.setText("CẬP NHẬT");
      btnUpdate.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
            btnUpdateActionPerformed(evt);
         }
      });

      btnRemove.setText("XÓA");
      btnRemove.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
            btnRemoveActionPerformed(evt);
         }
      });

      btnReset.setText("NHẬP MỚI");
      btnReset.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
            btnResetActionPerformed(evt);
         }
      });

      tblHocVien.setModel(new javax.swing.table.DefaultTableModel(
         new Object [][] {
            {null, null, null, null},
            {null, null, null, null},
            {null, null, null, null},
            {null, null, null, null}
         },
         new String [] {
            "Title 1", "Title 2", "Title 3", "Title 4"
         }
      ));
      tblHocVien.addMouseListener(new java.awt.event.MouseAdapter() {
         public void mouseClicked(java.awt.event.MouseEvent evt) {
            tblHocVienMouseClicked(evt);
         }
      });
      jScrollPane2.setViewportView(tblHocVien);

      btnSXDiem.setText("Sắp xếp theo điểm ");
      btnSXDiem.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
            btnSXDiemActionPerformed(evt);
         }
      });

      btnSXTen.setText("Sắp xếp theo tên");
      btnSXTen.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
            btnSXTenActionPerformed(evt);
         }
      });

      javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
      getContentPane().setLayout(layout);
      layout.setHorizontalGroup(
         layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(layout.createSequentialGroup()
            .addGap(29, 29, 29)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
               .addGroup(layout.createSequentialGroup()
                  .addGap(97, 97, 97)
                  .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                     .addComponent(chkThuong, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                     .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(txtXepLoai)
                        .addComponent(txtName, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(txtDiem, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(cboKhoaHoc, javax.swing.GroupLayout.Alignment.LEADING, 0, 312, Short.MAX_VALUE)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                           .addGap(50, 50, 50)
                           .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE))))
                  .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
               .addGroup(layout.createSequentialGroup()
                  .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                     .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                     .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel2)))
                  .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
               .addGroup(layout.createSequentialGroup()
                  .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                  .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
         .addGroup(layout.createSequentialGroup()
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 504, Short.MAX_VALUE)
            .addContainerGap())
         .addGroup(layout.createSequentialGroup()
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
               .addGroup(layout.createSequentialGroup()
                  .addGap(91, 91, 91)
                  .addComponent(btnAdd)
                  .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                  .addComponent(btnUpdate)
                  .addGap(18, 18, 18)
                  .addComponent(btnRemove)
                  .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                  .addComponent(btnReset))
               .addGroup(layout.createSequentialGroup()
                  .addContainerGap()
                  .addComponent(btnSXDiem)
                  .addGap(59, 59, 59)
                  .addComponent(btnSXTen)))
            .addGap(0, 0, Short.MAX_VALUE))
      );
      layout.setVerticalGroup(
         layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(layout.createSequentialGroup()
            .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(18, 18, 18)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
               .addComponent(jLabel2)
               .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGap(18, 18, 18)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
               .addComponent(txtDiem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
               .addComponent(jLabel3))
            .addGap(24, 24, 24)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
               .addComponent(jLabel4)
               .addComponent(cboKhoaHoc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGap(18, 18, 18)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
               .addComponent(jLabel5)
               .addComponent(txtXepLoai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGap(18, 18, 18)
            .addComponent(chkThuong)
            .addGap(18, 18, 18)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
               .addComponent(btnAdd)
               .addComponent(btnUpdate)
               .addComponent(btnRemove)
               .addComponent(btnReset))
            .addGap(18, 18, 18)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(2, 2, 2)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
               .addComponent(btnSXDiem)
               .addComponent(btnSXTen))
            .addContainerGap())
      );

      pack();
   }// </editor-fold>//GEN-END:initComponents

   private void cboKhoaHocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboKhoaHocActionPerformed
      // TODO add your handling code here:
   }//GEN-LAST:event_cboKhoaHocActionPerformed

   public boolean checkNull(){
      
      if(txtName.getText().isEmpty()){
         JOptionPane.showMessageDialog(this, "Vui lòng nhập Tên");
         txtName.requestFocus();
         return false;
      }
      else if(txtDiem.getText().isEmpty()){
         JOptionPane.showMessageDialog(this, "Vui lòng nhập Điểm");
         txtDiem.requestFocus();
         return false;
      }
      
      try{
         Double diem = Double.parseDouble(txtDiem.getText());
         if(diem >=0 && diem <= 10 ){
               return true;
         }
         else{
            JOptionPane.showMessageDialog(this, "Vui lòng nhập lại Điểm 0-10");
            txtDiem.requestFocus();
            return false;
         }
         
      }
      catch(Exception e){
         JOptionPane.showMessageDialog(null, "Vui lòng nhập Điểm đúng định dạng");
      }
     return false;
   }
   
   private void txtNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNameActionPerformed
      // TODO add your handling code here:
   }//GEN-LAST:event_txtNameActionPerformed

   public void addStudent(){
      if(checkNull()){
         String name = txtName.getText();
         String diem = txtDiem.getText();
         String khoahoc = (String) cboKhoaHoc.getSelectedItem();
         Student sv = new Student();
         sv.setName(name);
         sv.setMarks(Double.parseDouble(diem));
         sv.setCourse(khoahoc);
        dssv.add(sv);
        
        txtXepLoai.setText(sv.getGrade());
        chkThuong.setSelected(sv.isBonus());
        
//         JScrollPane scrollPane = new JScrollPane(tblHocVien);
//         tblHocVien.setFillsViewportHeight(true);


      }
   }
   
   public void loadDataToList(){
   
      dssv.add(new Student("Bình",9.5,"LẬP TRÌNH JAVA"));
      dssv.add(new Student("An",4.5,"THIẾT KẾ WEB"));
      dssv.add(new Student("Dũng",7.5,"LẬP TRÌNH C#"));
      dssv.add(new Student("Kiên",8.5,"LẬP TRÌNH PYTHON"));
   }
   
   public void fillToTable(){
      String [] headers = {"HỌ VÀ TÊN","ĐIỂM","KHÓA HỌC","XẾP LOẠI","THƯỞNG"};
      DefaultTableModel model = new DefaultTableModel(headers,0);
      
      for(Student st: dssv){
         Object [] row = new Object[]{st.getName(),st.getMarks(),st.getCourse(),
                        st.getGrade(),st.isBonus() ? "THƯỞNG":"KHÔNG"};
      model.addRow(row);
      }
      tblHocVien.setModel(model);
      adjustColumnWidths(tblHocVien);
   }
   
   public void adjustColumnWidths(JTable table) {
    // Lấy TableColumnModel từ JTable
      TableColumnModel columnModel = table.getColumnModel();

      // Điều chỉnh chiều rộng của cột "HỌ VÀ TÊN"
      TableColumn column0 = columnModel.getColumn(0);
      column0.setMinWidth(100);
      column0.setMaxWidth(300);
      column0.setPreferredWidth(150);

      // Điều chỉnh chiều rộng của cột "ĐIỂM"
      TableColumn column1 = columnModel.getColumn(1);
      column1.setPreferredWidth(50);

      // Điều chỉnh chiều rộng của cột "KHÓA HỌC"
      TableColumn column2 = columnModel.getColumn(2);
      column2.setPreferredWidth(200);

      
  }

   
   
   private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
      // TODO add your handling code here:
      this.addStudent();
      this.fillToTable();
   }//GEN-LAST:event_btnAddActionPerformed

   public void showDetailIndex(int i){
      //int index = tblHocVien.getSelectedRow();
      Student st = dssv.get(i);
      txtName.setText(st.getName());
      txtDiem.setText(String.valueOf(st.getMarks()));
      txtXepLoai.setText(st.getGrade());
      cboKhoaHoc.setSelectedItem(st.getCourse());
      chkThuong.setSelected(st.isBonus());
      //tblHocVien.setRowSelectionInterval(1, 1);

   }
   
   public void showDetail(){
      int index = tblHocVien.getSelectedRow();
      Student st = dssv.get(index);
      txtName.setText(st.getName());
      txtDiem.setText(String.valueOf(st.getMarks()));
      txtXepLoai.setText(st.getGrade());
      cboKhoaHoc.setSelectedItem(st.getCourse());
      chkThuong.setSelected(st.isBonus());
      //tblHocVien.setRowSelectionInterval(index,index);
   }
   
   private void tblHocVienMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblHocVienMouseClicked
      // TODO add your handling code here:
      this.showDetail();
   }//GEN-LAST:event_tblHocVienMouseClicked

   private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
      // TODO add your handling code here:
      int index = tblHocVien.getSelectedRow();
      Student st = dssv.get(index);
      st.setName(txtName.getText());
      st.setCourse(cboKhoaHoc.getSelectedItem().toString());
      st.setMarks(Double.parseDouble(txtDiem.getText()));
      txtXepLoai.setText(st.getGrade());
      chkThuong.setSelected(st.isBonus());
      this.fillToTable();
      tblHocVien.setRowSelectionInterval(index,index);
   }//GEN-LAST:event_btnUpdateActionPerformed

   public void removeStudent(){
      int index = tblHocVien.getSelectedRow();
      dssv.remove(index);
      
      
   }
   
   private void btnRemoveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemoveActionPerformed
      // TODO add your handling code here:
      this.removeStudent();
      this.fillToTable();
      txtName.setText("");
      txtDiem.setText("");
      txtXepLoai.setText("");
      cboKhoaHoc.setSelectedIndex(0);
      chkThuong.setSelected(false);
      
      tblHocVien.clearSelection();
      //showDetailIndex(0);
      // Chọn hàng thứ nhất khi ứng dụng khởi động
        tblHocVien.setRowSelectionInterval(0, 0);
   }//GEN-LAST:event_btnRemoveActionPerformed

   private void btnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetActionPerformed
      // TODO add your handling code here:
      txtName.setText("");
      txtDiem.setText("");
      txtXepLoai.setText("");
      cboKhoaHoc.setSelectedIndex(0);
      chkThuong.setSelected(false);
      tblHocVien.clearSelection();
   }//GEN-LAST:event_btnResetActionPerformed

   
   
   public void orderByName(){
      Comparator<Student> com = new Comparator<Student>(){
         public int compare(Student o1, Student o2){
         return o1.getName().compareTo(o2.getName());
         }
      };
      Collections.sort(dssv,com);
   }
   
   public void orderByMarks(){
      Comparator<Student> com = new Comparator<Student>(){
         public int compare(Student o1, Student o2){
            Double d1 = o1.getMarks();
            Double d2 = o2.getMarks();
         return d1.compareTo(d2);
         }
      };
      Collections.sort(dssv,com);
   }
   
   
   private void btnSXDiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSXDiemActionPerformed
      // TODO add your handling code here:
      this.orderByMarks();
      this.fillToTable();
   }//GEN-LAST:event_btnSXDiemActionPerformed

   private void btnSXTenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSXTenActionPerformed
      // TODO add your handling code here:
      this.orderByName();
      this.fillToTable();
   }//GEN-LAST:event_btnSXTenActionPerformed

   
   /**
    * @param args the command line arguments
    */
   public static void main(String args[]) {
      /* Set the Nimbus look and feel */
      //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
      /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
       */
      try {
         for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
            if ("Nimbus".equals(info.getName())) {
               javax.swing.UIManager.setLookAndFeel(info.getClassName());
               break;
            }
         }
      } catch (ClassNotFoundException ex) {
         java.util.logging.Logger.getLogger(Lab2_Bai1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
      } catch (InstantiationException ex) {
         java.util.logging.Logger.getLogger(Lab2_Bai1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
      } catch (IllegalAccessException ex) {
         java.util.logging.Logger.getLogger(Lab2_Bai1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
      } catch (javax.swing.UnsupportedLookAndFeelException ex) {
         java.util.logging.Logger.getLogger(Lab2_Bai1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
      }
      //</editor-fold>

      /* Create and display the form */
      java.awt.EventQueue.invokeLater(new Runnable() {
         public void run() {
            new Lab2_Bai1().setVisible(true);
         }
      });
   }

   // Variables declaration - do not modify//GEN-BEGIN:variables
   private javax.swing.JButton btnAdd;
   private javax.swing.JButton btnRemove;
   private javax.swing.JButton btnReset;
   private javax.swing.JButton btnSXDiem;
   private javax.swing.JButton btnSXTen;
   private javax.swing.JButton btnUpdate;
   private javax.swing.JComboBox<String> cboKhoaHoc;
   private javax.swing.JCheckBox chkThuong;
   private javax.swing.JLabel jLabel1;
   private javax.swing.JLabel jLabel2;
   private javax.swing.JLabel jLabel3;
   private javax.swing.JLabel jLabel4;
   private javax.swing.JLabel jLabel5;
   private javax.swing.JScrollPane jScrollPane1;
   private javax.swing.JScrollPane jScrollPane2;
   private javax.swing.JTable jTable1;
   private javax.swing.JTable tblHocVien;
   private javax.swing.JTextField txtDiem;
   private javax.swing.JTextField txtName;
   private javax.swing.JTextField txtXepLoai;
   // End of variables declaration//GEN-END:variables
}
