/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package LAB3;

import java.awt.Color;
import java.io.File;
import java.io.PrintWriter;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JColorChooser;
import javax.swing.JFileChooser;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author admin
 */
public class Lab3_Bai1 extends javax.swing.JFrame {

   /**
    * Creates new form Lab3_Bai1
    */
   public Lab3_Bai1() {
      initComponents();
      
      this.setResizable(false); // co kich thuoc
      //this.getContentPane().setBackground(Color.orange); // chinh mau
      this.setLocationRelativeTo(null);
   }

   /**
    * This method is called from within the constructor to initialize the form.
    * WARNING: Do NOT modify this code. The content of this method is always
    * regenerated by the Form Editor.
    */
   @SuppressWarnings("unchecked")
   // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
   private void initComponents() {

      jMenu1 = new javax.swing.JMenu();
      jMenu2 = new javax.swing.JMenu();
      jMenu3 = new javax.swing.JMenu();
      buttonGroup1 = new javax.swing.ButtonGroup();
      jPopupMenu1 = new javax.swing.JPopupMenu();
      jToolBar1 = new javax.swing.JToolBar();
      jToolBar2 = new javax.swing.JToolBar();
      jFileChooser1 = new javax.swing.JFileChooser();
      jToolBar3 = new javax.swing.JToolBar();
      btnReset = new javax.swing.JButton();
      btnAbout = new javax.swing.JButton();
      btnExit = new javax.swing.JButton();
      txtend = new javax.swing.JTextField();
      jScrollPane2 = new javax.swing.JScrollPane();
      expen = new javax.swing.JEditorPane();
      jMenuBar1 = new javax.swing.JMenuBar();
      meunNew = new javax.swing.JMenu();
      mnINew = new javax.swing.JMenuItem();
      mnIOpen = new javax.swing.JMenuItem();
      mnISave = new javax.swing.JMenuItem();
      jMenu5 = new javax.swing.JMenu();
      rbtnmnColorRed = new javax.swing.JRadioButtonMenuItem();
      rbtnmnColorGreen = new javax.swing.JRadioButtonMenuItem();
      rbtnmnColorBlue = new javax.swing.JRadioButtonMenuItem();
      rbtnmnChooseColor = new javax.swing.JRadioButtonMenuItem();
      mnSystem = new javax.swing.JMenu();
      mnAboutUs = new javax.swing.JMenuItem();
      mnExit = new javax.swing.JMenuItem();

      jMenu1.setText("jMenu1");

      jMenu2.setText("jMenu2");

      jMenu3.setText("jMenu3");

      jToolBar1.setRollover(true);

      jToolBar2.setRollover(true);

      setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

      jToolBar3.setRollover(true);

      btnReset.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/New.png"))); // NOI18N
      btnReset.setFocusable(false);
      btnReset.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
      btnReset.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
      btnReset.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
            btnResetActionPerformed(evt);
         }
      });
      jToolBar3.add(btnReset);

      btnAbout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/man-icon.png"))); // NOI18N
      btnAbout.setFocusable(false);
      btnAbout.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
      btnAbout.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
      btnAbout.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
            btnAboutActionPerformed(evt);
         }
      });
      jToolBar3.add(btnAbout);

      btnExit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/exit.png"))); // NOI18N
      btnExit.setFocusable(false);
      btnExit.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
      btnExit.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
      btnExit.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
            btnExitActionPerformed(evt);
         }
      });
      jToolBar3.add(btnExit);

      txtend.setEditable(false);
      txtend.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
      txtend.setHorizontalAlignment(javax.swing.JTextField.CENTER);
      txtend.setText("Fpoly - Java 2");

      jScrollPane2.setViewportView(expen);

      meunNew.setText("File");

      mnINew.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_N, java.awt.event.InputEvent.CTRL_DOWN_MASK));
      mnINew.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/New.png"))); // NOI18N
      mnINew.setText("New");
      mnINew.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
            mnINewActionPerformed(evt);
         }
      });
      meunNew.add(mnINew);

      mnIOpen.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_O, java.awt.event.InputEvent.CTRL_DOWN_MASK));
      mnIOpen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/Open.png"))); // NOI18N
      mnIOpen.setText("Open");
      mnIOpen.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
            mnIOpenActionPerformed(evt);
         }
      });
      meunNew.add(mnIOpen);

      mnISave.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.CTRL_DOWN_MASK));
      mnISave.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/Save.png"))); // NOI18N
      mnISave.setText("Save");
      mnISave.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
            mnISaveActionPerformed(evt);
         }
      });
      meunNew.add(mnISave);

      jMenuBar1.add(meunNew);

      jMenu5.setText("Color");

      buttonGroup1.add(rbtnmnColorRed);
      rbtnmnColorRed.setSelected(true);
      rbtnmnColorRed.setText("Red");
      rbtnmnColorRed.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
            rbtnmnColorRedActionPerformed(evt);
         }
      });
      jMenu5.add(rbtnmnColorRed);

      buttonGroup1.add(rbtnmnColorGreen);
      rbtnmnColorGreen.setText("Green");
      rbtnmnColorGreen.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
            rbtnmnColorGreenActionPerformed(evt);
         }
      });
      jMenu5.add(rbtnmnColorGreen);

      buttonGroup1.add(rbtnmnColorBlue);
      rbtnmnColorBlue.setText("Blue");
      rbtnmnColorBlue.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
            rbtnmnColorBlueActionPerformed(evt);
         }
      });
      jMenu5.add(rbtnmnColorBlue);

      buttonGroup1.add(rbtnmnChooseColor);
      rbtnmnChooseColor.setText("Text Color");
      rbtnmnChooseColor.addContainerListener(new java.awt.event.ContainerAdapter() {
         public void componentRemoved(java.awt.event.ContainerEvent evt) {
            rbtnmnChooseColorComponentRemoved(evt);
         }
      });
      rbtnmnChooseColor.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
            rbtnmnChooseColorActionPerformed(evt);
         }
      });
      jMenu5.add(rbtnmnChooseColor);

      jMenuBar1.add(jMenu5);

      mnSystem.setText("System");

      mnAboutUs.setText("About us");
      mnAboutUs.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
            mnAboutUsActionPerformed(evt);
         }
      });
      mnSystem.add(mnAboutUs);

      mnExit.setText("Exit");
      mnExit.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
            mnExitActionPerformed(evt);
         }
      });
      mnSystem.add(mnExit);

      jMenuBar1.add(mnSystem);

      setJMenuBar(jMenuBar1);

      javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
      getContentPane().setLayout(layout);
      layout.setHorizontalGroup(
         layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addComponent(jToolBar3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
         .addComponent(txtend, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 441, Short.MAX_VALUE)
         .addComponent(jScrollPane2)
      );
      layout.setVerticalGroup(
         layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(layout.createSequentialGroup()
            .addComponent(jToolBar3, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(txtend, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addContainerGap(9, Short.MAX_VALUE))
      );

      pack();
   }// </editor-fold>//GEN-END:initComponents

   private void mnINewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnINewActionPerformed
      // TODO add your handling code here:
      expen.setText("");
   }//GEN-LAST:event_mnINewActionPerformed

   private void mnISaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnISaveActionPerformed
      // TODO add your handling code here:
      JFileChooser file = new JFileChooser();
      int result = file.showOpenDialog(null);
      if(result == JFileChooser.APPROVE_OPTION){
         File fname = file.getSelectedFile();
         try{
            PrintWriter pw = new PrintWriter(fname);
            pw.println(expen.getText());
            pw.close();
         }catch(Exception e)
         {
            e.printStackTrace();
         }
         
      }
   }//GEN-LAST:event_mnISaveActionPerformed

   private void mnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnExitActionPerformed
      // TODO add your handling code here:
      int response =JOptionPane.showInternalConfirmDialog(null, 
              "Bạn có muốn tắt không?", "Xác nhận Thoát",
              JOptionPane.YES_NO_OPTION,
                JOptionPane.QUESTION_MESSAGE);
      if(response == JOptionPane.YES_OPTION){
         System.exit(0);
      }
   }//GEN-LAST:event_mnExitActionPerformed

   private void btnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetActionPerformed
      // TODO add your handling code here:
      expen.setText("");
      
   }//GEN-LAST:event_btnResetActionPerformed

   private void rbtnmnChooseColorComponentRemoved(java.awt.event.ContainerEvent evt) {//GEN-FIRST:event_rbtnmnChooseColorComponentRemoved
      // TODO add your handling code here:
   }//GEN-LAST:event_rbtnmnChooseColorComponentRemoved

   private void rbtnmnColorRedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtnmnColorRedActionPerformed
      // TODO add your handling code here:
      txtend.setBackground(Color.red);
   }//GEN-LAST:event_rbtnmnColorRedActionPerformed

   private void rbtnmnColorGreenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtnmnColorGreenActionPerformed
      // TODO add your handling code here:
       txtend.setBackground(Color.green);
   }//GEN-LAST:event_rbtnmnColorGreenActionPerformed

   private void btnAboutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAboutActionPerformed
      // TODO add your handling code here:
      SimpleDateFormat df = new SimpleDateFormat("dd-MM-yyyy");
      Date now = new Date();
      
      String str = "Program Demo Menu";
      str += "\nAuthor: Quang Huy";
      str += "\nLast Update: " + df.format(now);
      str += "\nEducation: Fpoly";
      JOptionPane.showMessageDialog(null, str,"Gioi thieu", JOptionPane.INFORMATION_MESSAGE);
   }//GEN-LAST:event_btnAboutActionPerformed

   private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
      int response =JOptionPane.showInternalConfirmDialog(null, 
              "Bạn có muốn tắt không?", "Xác nhận Thoát",
              JOptionPane.YES_NO_OPTION,
                JOptionPane.QUESTION_MESSAGE);
      if(response == JOptionPane.YES_OPTION){
         System.exit(0);
      }
   }//GEN-LAST:event_btnExitActionPerformed

   private void rbtnmnColorBlueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtnmnColorBlueActionPerformed
      // TODO add your handling code here:
      txtend.setBackground(Color.blue);
   }//GEN-LAST:event_rbtnmnColorBlueActionPerformed

   private void mnIOpenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnIOpenActionPerformed
      // TODO add your handling code here:
      JFileChooser file = new JFileChooser();
      int result = file.showOpenDialog(null);
      if(result == JFileChooser.APPROVE_OPTION){
         try{
            expen.setPage("file:///" + file.getSelectedFile().getPath());
         }catch(Exception e)
         {
            e.printStackTrace();
         }
         
      }
   }//GEN-LAST:event_mnIOpenActionPerformed

   private void mnAboutUsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnAboutUsActionPerformed
      // TODO add your handling code here:
      SimpleDateFormat df = new SimpleDateFormat("dd-MM-yyyy");
      Date now = new Date();
      
      String str = "Program Demo Menu";
      str += "\nAuthor: Quang Huy";
      str += "\nLast Update: " + df.format(now);
      str += "\nEducation: Fpoly";
      JOptionPane.showMessageDialog(null, str,"Gioi thieu", JOptionPane.INFORMATION_MESSAGE);
   }//GEN-LAST:event_mnAboutUsActionPerformed

   private void rbtnmnChooseColorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtnmnChooseColorActionPerformed
      // TODO add your handling code here:
      Color c = JColorChooser.showDialog(null, "Chọn màu chữ", Color.white);
      txtend.setForeground(c);
   }//GEN-LAST:event_rbtnmnChooseColorActionPerformed

   /**
    * @param args the command line arguments
    */
   public static void main(String args[]) {
      /* Set the Nimbus look and feel */
      //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
      /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
       */
      try {
         for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
            if ("Nimbus".equals(info.getName())) {
               javax.swing.UIManager.setLookAndFeel(info.getClassName());
               break;
            }
         }
      } catch (ClassNotFoundException ex) {
         java.util.logging.Logger.getLogger(Lab3_Bai1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
      } catch (InstantiationException ex) {
         java.util.logging.Logger.getLogger(Lab3_Bai1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
      } catch (IllegalAccessException ex) {
         java.util.logging.Logger.getLogger(Lab3_Bai1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
      } catch (javax.swing.UnsupportedLookAndFeelException ex) {
         java.util.logging.Logger.getLogger(Lab3_Bai1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
      }
      //</editor-fold>

      /* Create and display the form */
      java.awt.EventQueue.invokeLater(new Runnable() {
         public void run() {
            new Lab3_Bai1().setVisible(true);
         }
      });
   }

   // Variables declaration - do not modify//GEN-BEGIN:variables
   private javax.swing.JButton btnAbout;
   private javax.swing.JButton btnExit;
   private javax.swing.JButton btnReset;
   private javax.swing.ButtonGroup buttonGroup1;
   private javax.swing.JEditorPane expen;
   private javax.swing.JFileChooser jFileChooser1;
   private javax.swing.JMenu jMenu1;
   private javax.swing.JMenu jMenu2;
   private javax.swing.JMenu jMenu3;
   private javax.swing.JMenu jMenu5;
   private javax.swing.JMenuBar jMenuBar1;
   private javax.swing.JPopupMenu jPopupMenu1;
   private javax.swing.JScrollPane jScrollPane2;
   private javax.swing.JToolBar jToolBar1;
   private javax.swing.JToolBar jToolBar2;
   private javax.swing.JToolBar jToolBar3;
   private javax.swing.JMenu meunNew;
   private javax.swing.JMenuItem mnAboutUs;
   private javax.swing.JMenuItem mnExit;
   private javax.swing.JMenuItem mnINew;
   private javax.swing.JMenuItem mnIOpen;
   private javax.swing.JMenuItem mnISave;
   private javax.swing.JMenu mnSystem;
   private javax.swing.JRadioButtonMenuItem rbtnmnChooseColor;
   private javax.swing.JRadioButtonMenuItem rbtnmnColorBlue;
   private javax.swing.JRadioButtonMenuItem rbtnmnColorGreen;
   private javax.swing.JRadioButtonMenuItem rbtnmnColorRed;
   private javax.swing.JTextField txtend;
   // End of variables declaration//GEN-END:variables
}
