/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package LAB1;

import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author admin
 */
public class Lab1_Bai4 extends javax.swing.JFrame {

   /**
    * Creates new form Lab1_Bai4
    */
   public Lab1_Bai4() {
      initComponents();
      this.setTitle("Student Detail"); //tieu de
      //this.setSize(700,500); // khung
      this.setResizable(false); // co kich thuoc
      //this.getContentPane().setBackground(Color.orange); // chinh mau
      this.setLocationRelativeTo(null); // chinh o giua
   }

   /**
    * This method is called from within the constructor to initialize the form.
    * WARNING: Do NOT modify this code. The content of this method is always
    * regenerated by the Form Editor.
    */
   @SuppressWarnings("unchecked")
   // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
   private void initComponents() {

      group = new javax.swing.ButtonGroup();
      jLabel1 = new javax.swing.JLabel();
      txtname = new javax.swing.JTextField();
      jLabel2 = new javax.swing.JLabel();
      jScrollPane1 = new javax.swing.JScrollPane();
      txtA = new javax.swing.JTextArea();
      jLabel3 = new javax.swing.JLabel();
      jLabel4 = new javax.swing.JLabel();
      jPanel1 = new javax.swing.JPanel();
      chkboxread = new javax.swing.JCheckBox();
      chkboxsing = new javax.swing.JCheckBox();
      chkboxdance = new javax.swing.JCheckBox();
      jPanel2 = new javax.swing.JPanel();
      radioM = new javax.swing.JRadioButton();
      radioF = new javax.swing.JRadioButton();
      btnvali = new javax.swing.JButton();
      btnreset = new javax.swing.JButton();

      setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

      jLabel1.setText("Name:");

      txtname.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
            txtnameActionPerformed(evt);
         }
      });

      jLabel2.setText("Address:");

      txtA.setColumns(20);
      txtA.setRows(5);
      jScrollPane1.setViewportView(txtA);

      jLabel3.setText("Sex:");

      jLabel4.setText("Hobby:");

      jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

      chkboxread.setText("Reading");
      chkboxread.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
            chkboxreadActionPerformed(evt);
         }
      });

      chkboxsing.setText("Singing");

      chkboxdance.setText("Dancing");

      javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
      jPanel1.setLayout(jPanel1Layout);
      jPanel1Layout.setHorizontalGroup(
         jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(jPanel1Layout.createSequentialGroup()
            .addContainerGap()
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
               .addComponent(chkboxread, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
               .addComponent(chkboxsing, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
               .addComponent(chkboxdance, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
      );
      jPanel1Layout.setVerticalGroup(
         jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(jPanel1Layout.createSequentialGroup()
            .addComponent(chkboxread)
            .addGap(8, 8, 8)
            .addComponent(chkboxsing)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
            .addComponent(chkboxdance)
            .addContainerGap(13, Short.MAX_VALUE))
      );

      jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

      group.add(radioM);
      radioM.setText("Male");
      radioM.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
            radioMActionPerformed(evt);
         }
      });

      group.add(radioF);
      radioF.setText("Female");

      javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
      jPanel2.setLayout(jPanel2Layout);
      jPanel2Layout.setHorizontalGroup(
         jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(jPanel2Layout.createSequentialGroup()
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
               .addComponent(radioM, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
               .addComponent(radioF, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGap(0, 0, Short.MAX_VALUE))
      );
      jPanel2Layout.setVerticalGroup(
         jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(jPanel2Layout.createSequentialGroup()
            .addGap(17, 17, 17)
            .addComponent(radioM)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(radioF)
            .addContainerGap())
      );

      btnvali.setText("Validate");
      btnvali.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
            btnvaliActionPerformed(evt);
         }
      });

      btnreset.setText("Reset");
      btnreset.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
            btnresetActionPerformed(evt);
         }
      });

      javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
      getContentPane().setLayout(layout);
      layout.setHorizontalGroup(
         layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(layout.createSequentialGroup()
            .addContainerGap()
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
               .addGroup(layout.createSequentialGroup()
                  .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                  .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                  .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 226, Short.MAX_VALUE)
                  .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                  .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
               .addGroup(layout.createSequentialGroup()
                  .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                     .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                     .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtname, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)))
                  .addGap(0, 0, Short.MAX_VALUE)))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addContainerGap())
         .addGroup(layout.createSequentialGroup()
            .addGap(149, 149, 149)
            .addComponent(btnvali)
            .addGap(28, 28, 28)
            .addComponent(btnreset)
            .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
      );
      layout.setVerticalGroup(
         layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(layout.createSequentialGroup()
            .addGap(16, 16, 16)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
               .addComponent(jLabel1)
               .addComponent(txtname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
               .addComponent(jLabel2)
               .addComponent(jLabel4)
               .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
               .addComponent(jScrollPane1))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
               .addGroup(layout.createSequentialGroup()
                  .addGap(17, 17, 17)
                  .addComponent(jLabel3))
               .addGroup(layout.createSequentialGroup()
                  .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                  .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
               .addComponent(btnvali)
               .addComponent(btnreset))
            .addContainerGap(19, Short.MAX_VALUE))
      );

      pack();
   }// </editor-fold>//GEN-END:initComponents

   private void chkboxreadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkboxreadActionPerformed
      // TODO add your handling code here:
   }//GEN-LAST:event_chkboxreadActionPerformed

   private void radioMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioMActionPerformed
      // TODO add your handling code here:
   }//GEN-LAST:event_radioMActionPerformed

   private void txtnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtnameActionPerformed
      // TODO add your handling code here:
   }//GEN-LAST:event_txtnameActionPerformed

   public boolean checkNull(){
      boolean read = chkboxread.isSelected();
      boolean sing = chkboxsing.isSelected();
      boolean dance = chkboxdance.isSelected();
      if(txtname.getText().isEmpty()){
         JOptionPane.showMessageDialog(this, "Vui lòng nhap Ten");
         txtname.requestFocus();
         return false;
      }
      else if(txtA.getText().isEmpty()){
         JOptionPane.showMessageDialog(this, "Vui long nhap Dia chi");
         txtA.requestFocus();
         return false;
      }
      else if(read == false && sing == false && dance == false){
         JOptionPane.showMessageDialog(this, "Vui long Chon so thich");
         jPanel1.requestFocus();
         return false;
      }
      else if(radioM.isSelected() == false && radioF.isSelected() == false){
         JOptionPane.showMessageDialog(this, "Vui long Chon gioi tinh");
         jPanel2.requestFocus();
         return false;
      }
      
      else return true;
   }
   public static ArrayList<String> checkbox = new ArrayList<String>();
   private void btnvaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnvaliActionPerformed
      // TODO add your handling code here:
      if(checkNull()){
         String name = txtname.getText();
         String address = txtA.getText();
         boolean read = chkboxread.isSelected();
         boolean sing = chkboxsing.isSelected();
         boolean dance = chkboxdance.isSelected();
         boolean male = radioM.isSelected();
         boolean female = radioF.isSelected();
         
         String sex ;
         if(male == true){
            
            sex = "Male";
            
         }else sex = "Female";

         checkbox.removeAll(checkbox);
         
         if(read){
            checkbox.add("Reading");
         } 
         if(sing){
            checkbox.add("Singing");
         }
         if(dance)
            checkbox.add("Dancing");
         
         
         JOptionPane.showMessageDialog(this, "Name: "+ name + 
                 ", Address: " + address +
                 ", Sex: " + sex + 
                 ", Hobby: "+ checkbox.toString());
      }
   }//GEN-LAST:event_btnvaliActionPerformed

   private void btnresetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnresetActionPerformed
      // TODO add your handling code here:
      
         txtname.setText("");
         txtA.setText("");
         chkboxread.setSelected(false);
         chkboxsing.setSelected(false);
         chkboxdance.setSelected(false);
         //radioM.setSelected(false);
         //radioF.setSelected(false);
         group.clearSelection();
         
         JOptionPane.showMessageDialog(this, "Ban click Reset");
   }//GEN-LAST:event_btnresetActionPerformed

   /**
    * @param args the command line arguments
    */
   public static void main(String args[]) {
      /* Set the Nimbus look and feel */
      //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
      /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
       */
      try {
         for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
            if ("Nimbus".equals(info.getName())) {
               javax.swing.UIManager.setLookAndFeel(info.getClassName());
               break;
            }
         }
      } catch (ClassNotFoundException ex) {
         java.util.logging.Logger.getLogger(Lab1_Bai4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
      } catch (InstantiationException ex) {
         java.util.logging.Logger.getLogger(Lab1_Bai4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
      } catch (IllegalAccessException ex) {
         java.util.logging.Logger.getLogger(Lab1_Bai4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
      } catch (javax.swing.UnsupportedLookAndFeelException ex) {
         java.util.logging.Logger.getLogger(Lab1_Bai4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
      }
      //</editor-fold>

      /* Create and display the form */
      java.awt.EventQueue.invokeLater(new Runnable() {
         public void run() {
            new Lab1_Bai4().setVisible(true);
         }
      });
   }

   // Variables declaration - do not modify//GEN-BEGIN:variables
   private javax.swing.JButton btnreset;
   private javax.swing.JButton btnvali;
   private javax.swing.JCheckBox chkboxdance;
   private javax.swing.JCheckBox chkboxread;
   private javax.swing.JCheckBox chkboxsing;
   private javax.swing.ButtonGroup group;
   private javax.swing.JLabel jLabel1;
   private javax.swing.JLabel jLabel2;
   private javax.swing.JLabel jLabel3;
   private javax.swing.JLabel jLabel4;
   private javax.swing.JPanel jPanel1;
   private javax.swing.JPanel jPanel2;
   private javax.swing.JScrollPane jScrollPane1;
   private javax.swing.JRadioButton radioF;
   private javax.swing.JRadioButton radioM;
   private javax.swing.JTextArea txtA;
   private javax.swing.JTextField txtname;
   // End of variables declaration//GEN-END:variables
}
