/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package LAB1;

import java.awt.Color;
import javax.swing.JOptionPane;

/**
 *
 * @author admin
 */
public class Lab1_Bai1 extends javax.swing.JFrame {

   /**
    * Creates new form Caculator
    */
   public Lab1_Bai1() {
      initComponents();
      
      this.setTitle("Calculator"); //tieu de
      this.setSize(500,300); // khung
      this.setResizable(false); // co kich thuoc
      this.getContentPane().setBackground(Color.orange); // chinh mau
      this.setLocationRelativeTo(null); // chinh o giua
      
   }

   /**
    * This method is called from within the constructor to initialize the form.
    * WARNING: Do NOT modify this code. The content of this method is always
    * regenerated by the Form Editor.
    */
   @SuppressWarnings("unchecked")
   // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
   private void initComponents() {

      jLabel1 = new javax.swing.JLabel();
      jLabel2 = new javax.swing.JLabel();
      txt1 = new javax.swing.JTextField();
      txt2 = new javax.swing.JTextField();
      jLabel3 = new javax.swing.JLabel();
      txtkq = new javax.swing.JTextField();
      btncong = new javax.swing.JButton();
      btntru = new javax.swing.JButton();
      btnnhan = new javax.swing.JButton();
      btnchia = new javax.swing.JButton();
      btnluythua = new javax.swing.JButton();

      setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

      jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
      jLabel1.setText("First number:");

      jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
      jLabel2.setText("Second number:");

      txt1.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
            txt1ActionPerformed(evt);
         }
      });

      txt2.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
            txt2ActionPerformed(evt);
         }
      });

      jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
      jLabel3.setText("Result:");

      txtkq.setEditable(false);
      txtkq.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
            txtkqActionPerformed(evt);
         }
      });

      btncong.setText("+");
      btncong.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
            btncongActionPerformed(evt);
         }
      });

      btntru.setText("-");
      btntru.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
            btntruActionPerformed(evt);
         }
      });

      btnnhan.setText("*");
      btnnhan.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
            btnnhanActionPerformed(evt);
         }
      });

      btnchia.setText("/");
      btnchia.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
            btnchiaActionPerformed(evt);
         }
      });

      btnluythua.setText("Luy Thua");
      btnluythua.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
            btnluythuaActionPerformed(evt);
         }
      });

      javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
      getContentPane().setLayout(layout);
      layout.setHorizontalGroup(
         layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
            .addGap(54, 54, 54)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
               .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
               .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
               .addGroup(layout.createSequentialGroup()
                  .addGap(56, 56, 56)
                  .addComponent(btncong))
               .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
               .addGroup(layout.createSequentialGroup()
                  .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                     .addComponent(txt2)
                     .addComponent(txtkq)
                     .addComponent(txt1))
                  .addGap(35, 35, 35))
               .addGroup(layout.createSequentialGroup()
                  .addComponent(btntru)
                  .addGap(42, 42, 42)
                  .addComponent(btnnhan)
                  .addGap(35, 35, 35)
                  .addComponent(btnchia)
                  .addGap(18, 18, 18)
                  .addComponent(btnluythua)
                  .addGap(0, 0, Short.MAX_VALUE))))
      );
      layout.setVerticalGroup(
         layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(layout.createSequentialGroup()
            .addGap(56, 56, 56)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
               .addComponent(jLabel1)
               .addComponent(txt1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGap(19, 19, 19)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
               .addComponent(jLabel2)
               .addComponent(txt2, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGap(18, 18, 18)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
               .addComponent(jLabel3)
               .addComponent(txtkq, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 46, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
               .addComponent(btntru)
               .addComponent(btnnhan)
               .addComponent(btncong)
               .addComponent(btnchia)
               .addComponent(btnluythua))
            .addGap(37, 37, 37))
      );

      pack();
   }// </editor-fold>//GEN-END:initComponents

   private void txt1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt1ActionPerformed
      // TODO add your handling code here:
   }//GEN-LAST:event_txt1ActionPerformed

   private void txt2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt2ActionPerformed
      // TODO add your handling code here:
   }//GEN-LAST:event_txt2ActionPerformed

   private void txtkqActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtkqActionPerformed
      // TODO add your handling code here:
   }//GEN-LAST:event_txtkqActionPerformed

   public boolean checkNull(){
   
      if(txt1.getText().equals("")){
      JOptionPane.showMessageDialog(this, "Chua nhap gia tri");
      txt1.requestFocus();
      return false;
      }else if(txt2.getText().equals("")){
      JOptionPane.showMessageDialog(this, "Chua nhap gia tri");
      txt2.requestFocus();
      return false;
      }else return true;
   }
   
   private void btncongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncongActionPerformed
      // TODO add your handling code here:
//      try{
//         Double so1 = Double.parseDouble(txt1.getText());
//      Double so2 = Double.parseDouble(txt2.getText());
//      Double kq = so1 + so2;
//      
//      txtkq.setText(String.valueOf(kq));
//      }
//      catch(Exception e){
//      //JOptionPane.showMessageDialog(null, "Please input your name");
//      JOptionPane.showMessageDialog(null, "Please input your name");
//      }
      float so1,so2;
      double kq;
      if(checkNull()){
      so1 = Float.parseFloat(txt1.getText());
      so2 = Float.parseFloat(txt2.getText());
      kq = so1 + so2;
      txtkq.setText(kq+"");
      }
   }//GEN-LAST:event_btncongActionPerformed

   private void btntruActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btntruActionPerformed
      // TODO add your handling code here:
      try{
      Double so1 = Double.parseDouble(txt1.getText());
      Double so2 = Double.parseDouble(txt2.getText());
      Double kq = so1 - so2;
      txtkq.setText(String.valueOf(kq));
      }
      catch(Exception e){
      //JOptionPane.showMessageDialog(null, "Please input your name");
      JOptionPane.showMessageDialog(null, "Please input your name");
      }
   }//GEN-LAST:event_btntruActionPerformed

   private void btnnhanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnnhanActionPerformed
      // TODO add your handling code here:
      try{
      Double so1 = Double.parseDouble(txt1.getText());
      Double so2 = Double.parseDouble(txt2.getText());
      Double kq = so1 * so2;
      txtkq.setText(String.valueOf(kq));
      }
      catch(Exception e){
      //JOptionPane.showMessageDialog(null, "Please input your name");
      JOptionPane.showMessageDialog(null, "Please input your name");
      }
   }//GEN-LAST:event_btnnhanActionPerformed

   private void btnchiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnchiaActionPerformed
      // TODO add your handling code here:
      try{
      Double so1 = Double.parseDouble(txt1.getText());
      Double so2 = Double.parseDouble(txt2.getText());
      Double kq = so1 / so2;
      txtkq.setText(String.valueOf(kq));
      }
      catch(Exception e){
      //JOptionPane.showMessageDialog(null, "Please input your name");
      JOptionPane.showMessageDialog(null, "Please input your name");
      }
   }//GEN-LAST:event_btnchiaActionPerformed

   private void btnluythuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnluythuaActionPerformed
      // TODO add your handling code here:
      try{
      Double so1 = Double.parseDouble(txt1.getText());
      int so2 = Integer.parseInt(txt2.getText());
      Double kq =1.0;
      for(int i =1; i<=so2; i++){
      kq *= so1;
      }
      txtkq.setText(kq+ "");
      }
      catch(Exception e){
      //JOptionPane.showMessageDialog(null, "Please input your name");
      JOptionPane.showMessageDialog(null, "Please input your name");
      }
   }//GEN-LAST:event_btnluythuaActionPerformed

   /**
    * @param args the command line arguments
    */
   public static void main(String args[]) {
      /* Set the Nimbus look and feel */
      //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
      /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
       */
      try {
         for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
            if ("Nimbus".equals(info.getName())) {
               javax.swing.UIManager.setLookAndFeel(info.getClassName());
               break;
            }
         }
      } catch (ClassNotFoundException ex) {
         java.util.logging.Logger.getLogger(Lab1_Bai1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
      } catch (InstantiationException ex) {
         java.util.logging.Logger.getLogger(Lab1_Bai1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
      } catch (IllegalAccessException ex) {
         java.util.logging.Logger.getLogger(Lab1_Bai1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
      } catch (javax.swing.UnsupportedLookAndFeelException ex) {
         java.util.logging.Logger.getLogger(Lab1_Bai1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
      }
      //</editor-fold>
      //</editor-fold>

      /* Create and display the form */
      java.awt.EventQueue.invokeLater(new Runnable() {
         public void run() {
            new Lab1_Bai1().setVisible(true);
         }
      });
   }

   // Variables declaration - do not modify//GEN-BEGIN:variables
   private javax.swing.JButton btnchia;
   private javax.swing.JButton btncong;
   private javax.swing.JButton btnluythua;
   private javax.swing.JButton btnnhan;
   private javax.swing.JButton btntru;
   private javax.swing.JLabel jLabel1;
   private javax.swing.JLabel jLabel2;
   private javax.swing.JLabel jLabel3;
   private javax.swing.JTextField txt1;
   private javax.swing.JTextField txt2;
   private javax.swing.JTextField txtkq;
   // End of variables declaration//GEN-END:variables
}
