/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package LAB1;

import java.awt.event.ItemListener;
import java.util.Arrays;
import javax.swing.JCheckBox;
import javax.swing.JOptionPane;

/**
 *
 * @author admin
 */
public class Lab1_Bai3 extends javax.swing.JFrame {

   /**
    * Creates new form Lab1_Bai3
    */
   public Lab1_Bai3() {
      initComponents();
      
      this.setTitle("Login"); //tieu de
      this.setSize(400,300); // khung
      this.setResizable(false); // co kich thuoc
      //this.getContentPane().setBackground(Color.orange); // chinh mau
      this.setLocationRelativeTo(null); // chinh o giua
   }

   /**
    * This method is called from within the constructor to initialize the form.
    * WARNING: Do NOT modify this code. The content of this method is always
    * regenerated by the Form Editor.
    */
   @SuppressWarnings("unchecked")
   // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
   private void initComponents() {

      jLabel1 = new javax.swing.JLabel();
      jLabel2 = new javax.swing.JLabel();
      jLabel3 = new javax.swing.JLabel();
      txtuser = new javax.swing.JTextField();
      txtpass = new javax.swing.JPasswordField();
      chkbox1 = new javax.swing.JCheckBox();
      btnlogin = new javax.swing.JButton();
      btnreset = new javax.swing.JButton();

      setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

      jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
      jLabel1.setForeground(new java.awt.Color(0, 0, 255));
      jLabel1.setText("LOGIN FORM");

      jLabel2.setText("Username");

      jLabel3.setText("Password");

      txtuser.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
            txtuserActionPerformed(evt);
         }
      });

      txtpass.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
            txtpassActionPerformed(evt);
         }
      });

      chkbox1.setSelected(true);
      chkbox1.setText("Remember me?");
      chkbox1.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
            chkbox1ActionPerformed(evt);
         }
      });

      btnlogin.setText("Login");
      btnlogin.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
            btnloginActionPerformed(evt);
         }
      });

      btnreset.setText("Reset");
      btnreset.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
            btnresetActionPerformed(evt);
         }
      });

      javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
      getContentPane().setLayout(layout);
      layout.setHorizontalGroup(
         layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(layout.createSequentialGroup()
            .addContainerGap()
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
               .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
               .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 61, Short.MAX_VALUE))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
               .addGroup(layout.createSequentialGroup()
                  .addComponent(btnlogin)
                  .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                  .addComponent(btnreset))
               .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                  .addComponent(txtuser)
                  .addComponent(txtpass, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE))
               .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
               .addComponent(chkbox1, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addContainerGap(141, Short.MAX_VALUE))
      );
      layout.setVerticalGroup(
         layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(layout.createSequentialGroup()
            .addGap(5, 5, 5)
            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(18, 18, 18)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
               .addComponent(jLabel2)
               .addComponent(txtuser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGap(18, 18, 18)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
               .addComponent(jLabel3)
               .addComponent(txtpass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGap(18, 18, 18)
            .addComponent(chkbox1)
            .addGap(18, 18, 18)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
               .addComponent(btnlogin)
               .addComponent(btnreset))
            .addContainerGap(109, Short.MAX_VALUE))
      );

      pack();
   }// </editor-fold>//GEN-END:initComponents

   public boolean checkNull(){
      if(txtuser.getText().isEmpty()){
         JOptionPane.showMessageDialog(this, "Vui lòng nhap User");
         txtuser.requestFocus();
         return false;
      }
      else if(txtpass.getPassword().length ==0){
         JOptionPane.showMessageDialog(this, "Vui long nhap Password");
         txtpass.requestFocus();
         return false;
      }else return true;
   }
   
   private void txtuserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtuserActionPerformed
      // TODO add your handling code here:
   }//GEN-LAST:event_txtuserActionPerformed

   private void txtpassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtpassActionPerformed
      // TODO add your handling code here:
   }//GEN-LAST:event_txtpassActionPerformed

   private void btnloginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnloginActionPerformed
      // TODO add your handling code here:
      char[] correctPass = "polytechnic".toCharArray();
      if(checkNull()){
         String user = txtuser.getText();
         char[] pass = txtpass.getPassword();
         boolean check = chkbox1.isSelected();
         
         if(user.equals("fpt") && Arrays.equals(pass,correctPass)){
            JOptionPane.showMessageDialog(this, "Ban Login thanh cong");
           
            if(!check){
               txtuser.setText("");
               txtpass.setText("");
               JOptionPane.showMessageDialog(this, "Tai Khoan ban Khong ghi nho");
            }else{
               JOptionPane.showMessageDialog(this, "Tai Khoan ban da ghi nho");
            }
         }
         else{
            JOptionPane.showMessageDialog(this, "Ban Login that bai");
            if(!check){
               txtuser.setText("");
               txtpass.setText("");
               JOptionPane.showMessageDialog(this, "Tai Khoan ban Khong ghi nho");
            }
         }
      }
 
   }//GEN-LAST:event_btnloginActionPerformed

   private void btnresetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnresetActionPerformed
      // TODO add your handling code here:
      JOptionPane.showMessageDialog(this, "Reset click");
      chkbox1.setSelected(true);
      txtuser.setText("");
      txtpass.setText("");
   }//GEN-LAST:event_btnresetActionPerformed

   private void chkbox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkbox1ActionPerformed
      // TODO add your handling code here:
      
   }//GEN-LAST:event_chkbox1ActionPerformed

   /**
    * @param args the command line arguments
    */
   public static void main(String args[]) {
      /* Set the Nimbus look and feel */
      //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
      /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
       */
      try {
         for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
            if ("Nimbus".equals(info.getName())) {
               javax.swing.UIManager.setLookAndFeel(info.getClassName());
               break;
            }
         }
      } catch (ClassNotFoundException ex) {
         java.util.logging.Logger.getLogger(Lab1_Bai3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
      } catch (InstantiationException ex) {
         java.util.logging.Logger.getLogger(Lab1_Bai3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
      } catch (IllegalAccessException ex) {
         java.util.logging.Logger.getLogger(Lab1_Bai3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
      } catch (javax.swing.UnsupportedLookAndFeelException ex) {
         java.util.logging.Logger.getLogger(Lab1_Bai3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
      }
      //</editor-fold>

      /* Create and display the form */
      java.awt.EventQueue.invokeLater(new Runnable() {
         public void run() {
            new Lab1_Bai3().setVisible(true);
         }
      });
   }

   // Variables declaration - do not modify//GEN-BEGIN:variables
   private javax.swing.JButton btnlogin;
   private javax.swing.JButton btnreset;
   private javax.swing.JCheckBox chkbox1;
   private javax.swing.JLabel jLabel1;
   private javax.swing.JLabel jLabel2;
   private javax.swing.JLabel jLabel3;
   private javax.swing.JPasswordField txtpass;
   private javax.swing.JTextField txtuser;
   // End of variables declaration//GEN-END:variables
}
