/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package LAB1;

import javax.swing.JOptionPane;

/**
 *
 * @author admin
 */
public class Lab1_Bai2 extends javax.swing.JFrame {

   /**
    * Creates new form Lab1_Bai2
    */
   public Lab1_Bai2() {
      initComponents();
      
      this.setTitle("JOption Pane Example"); //tieu de
      this.setSize(300,200); // khung
      this.setResizable(false); // co kich thuoc
      //this.getContentPane().setBackground(Color.orange); // chinh mau
      this.setLocationRelativeTo(null); // chinh o giua
   }

   /**
    * This method is called from within the constructor to initialize the form.
    * WARNING: Do NOT modify this code. The content of this method is always
    * regenerated by the Form Editor.
    */
   @SuppressWarnings("unchecked")
   // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
   private void initComponents() {

      btn1 = new javax.swing.JButton();
      btn2 = new javax.swing.JButton();
      btn3 = new javax.swing.JButton();
      btn4 = new javax.swing.JButton();

      setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

      btn1.setText("Message Dialog");
      btn1.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
            btn1ActionPerformed(evt);
         }
      });

      btn2.setText("Input Dialog");
      btn2.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
            btn2ActionPerformed(evt);
         }
      });

      btn3.setText("Confirm Dialog");
      btn3.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
            btn3ActionPerformed(evt);
         }
      });

      btn4.setText("Option Dialog");
      btn4.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
            btn4ActionPerformed(evt);
         }
      });

      javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
      getContentPane().setLayout(layout);
      layout.setHorizontalGroup(
         layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(layout.createSequentialGroup()
            .addGap(18, 18, 18)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
               .addComponent(btn3)
               .addComponent(btn1))
            .addGap(41, 41, 41)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
               .addComponent(btn2, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
               .addComponent(btn4))
            .addContainerGap(119, Short.MAX_VALUE))
      );
      layout.setVerticalGroup(
         layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(layout.createSequentialGroup()
            .addGap(35, 35, 35)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
               .addComponent(btn1)
               .addComponent(btn2))
            .addGap(24, 24, 24)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
               .addComponent(btn3)
               .addComponent(btn4))
            .addContainerGap(197, Short.MAX_VALUE))
      );

      pack();
   }// </editor-fold>//GEN-END:initComponents

   private void btn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn1ActionPerformed
      // TODO add your handling code here:
      JOptionPane.showMessageDialog(this,"Please input your name");
   }//GEN-LAST:event_btn1ActionPerformed

   private void btn3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn3ActionPerformed
      // TODO add your handling code here:
      int ret = JOptionPane.showConfirmDialog(this, "Are you sure?"
              , "Confirm", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
      if(ret == JOptionPane.YES_OPTION){
         // Xử lý trường hợp người dùng chọn Yes
         JOptionPane.showMessageDialog(this,"Thank You, See you later");
      }else{
         // Xử lý trường hợp người dùng chọn No
         JOptionPane.showMessageDialog(this,"Thanks");
      }
   }//GEN-LAST:event_btn3ActionPerformed

   private void btn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn2ActionPerformed
      // TODO add your handling code here:
      String yourName = JOptionPane.showInputDialog("Your name is");
      
      // Có thể sử dụng !yourName.isEmpty() thay thế !yourName.equals("")để kiểm tra
      if(yourName != null && !yourName.equals("")){
         JOptionPane.showMessageDialog(this, "Your name is "+ yourName);
      }else{
         JOptionPane.showMessageDialog(this,"Please input your name");
      }
   }//GEN-LAST:event_btn2ActionPerformed

   private void btn4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn4ActionPerformed
      // TODO add your handling code here:
      int messageType = JOptionPane.QUESTION_MESSAGE;
      String[] options = {"Java","C++","VB","PHP","Perl"};
      int code = JOptionPane.showOptionDialog(this, 
              "What language do you prefer?", 
              "Option Dialog Box",0,messageType,
              null,options,"PHP");
      JOptionPane.showMessageDialog(this, "Answer: " + code);
   }//GEN-LAST:event_btn4ActionPerformed

   /**
    * @param args the command line arguments
    */
   public static void main(String args[]) {
      /* Set the Nimbus look and feel */
      //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
      /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
       */
      try {
         for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
            if ("Nimbus".equals(info.getName())) {
               javax.swing.UIManager.setLookAndFeel(info.getClassName());
               break;
            }
         }
      } catch (ClassNotFoundException ex) {
         java.util.logging.Logger.getLogger(Lab1_Bai2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
      } catch (InstantiationException ex) {
         java.util.logging.Logger.getLogger(Lab1_Bai2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
      } catch (IllegalAccessException ex) {
         java.util.logging.Logger.getLogger(Lab1_Bai2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
      } catch (javax.swing.UnsupportedLookAndFeelException ex) {
         java.util.logging.Logger.getLogger(Lab1_Bai2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
      }
      //</editor-fold>

      /* Create and display the form */
      java.awt.EventQueue.invokeLater(new Runnable() {
         public void run() {
            new Lab1_Bai2().setVisible(true);
         }
      });
   }

   // Variables declaration - do not modify//GEN-BEGIN:variables
   private javax.swing.JButton btn1;
   private javax.swing.JButton btn2;
   private javax.swing.JButton btn3;
   private javax.swing.JButton btn4;
   // End of variables declaration//GEN-END:variables
}
